dist: trusty

language: node_js
node_js:
  - 10

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - export DISPLAY=":99.0"
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test-single-run
  - (npm start > /dev/null &) && npm run protractor
