dist: trusty

language: node_js
node_js:
  - 10

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

script:
  - npm run test-single-run -- --browsers ChromeHeadless
  - (npm start > /dev/null &) && npm run protractor -- --capabilities.chromeOptions.args headless
